# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ab5a003d6c38c130552e6f0a95f5a74c8d2b1eefa4afe8a8ec3efddba967ed31fe62f9b0fb8edfa4f9d60a77f4cf3bac656d4b7e54627124fa63ad8cd7d0f9c

test:
  secret_key_base: 5d7bb73c802259f2b985ea57feb198395a62bce04e782029d3704745e2df5a4e437c32ad5e91ca8e5cd0a48e64a065d4ef42a44652eb9ec083002f356d72bb43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
